'use client'
import { Provider } from 'react-redux'
import { store } from './redux/reduxStateStore'
import './globals.css'
import SearchBar from './components/SearchBar'
import Logo from './components/Logo'
import Menu from './components/Menu'
import Bottom from './components/Bottom'
import reduxProvider from './redux/reduxProvider'

export const metadata = {
  title: 'Anime Paradise',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <Provider store={store}>
    <html lang="en">
      <body>
        <header>
            <SearchBar />
          <Logo />
          <Menu />
        </header>
        <main>
            {children}
        </main>
        <footer>
          <Bottom />
        </footer>
      </body>
    </html>
    </Provider>
  )
}