'use client'
import { useEffect } from 'react'
import { Provider, useDispatch } from 'react-redux'
import { store } from './redux/reduxStateStore'
import { fetchProducts } from './redux/fetchDataReducer'
import './globals.css'
import SearchBar from './components/SearchBar'
import Logo from './components/Logo'
import Menu from './components/Menu'
import Bottom from './components/Bottom'

export const metadata = {
  title: 'Anime Paradise',
  description: 'Generated by create next app',
}

export default function RootLayout({children}) {
  return (
    <Provider store={store}>
      <App>
        {children}
      </App>
    </Provider>
  )
}

function App({ children }) {
  const dispatch = useDispatch();
    useEffect(() => {
        dispatch(fetchProducts());
    }, [dispatch])

  return (
    <html lang="en">
      <body>
        <header>
          <SearchBar />
          <Logo />
          <Menu />
        </header>
        <main>
            {children}
        </main>
        <footer>
          <Bottom />
        </footer>
      </body>
    </html>
  )
}